### ISSUE TITLE
Prepare new data for NLLB-200

### ISSUE THREAD

**Issue by ibtiRaj** [facebookresearch/stopes#24]
Hi, I'm trying to fine tune NLLB-200 model on new bilingual data.  So I need to prepare my data  using prepare_data pipeline: https://github.com/facebookresearch/stopes/tree/main/stopes/pipelines/prepare_data
 there are my configs file:
![image](https://user-images.githubusercontent.com/50990415/217801860-8ad849fe-6208-4d08-abd2-48509555d432.png)

![image](https://user-images.githubusercontent.com/50990415/217801943-afd853a2-94b9-41dd-a870-d4a508380826.png)

![image](https://user-images.githubusercontent.com/50990415/217802077-829996fb-f1f0-424f-ae29-502c7c6325d1.png)

My output directory is the following:  
![image](https://user-images.githubusercontent.com/50990415/217802492-cd6bf829-83c7-4e9a-8448-fe347f3c41c6.png)

But I encountered a problem when fine tuning NLLb-200:
/usr/local/lib/python3.8/dist-packages/hydra/experimental/initialize.py:43: UserWarning: hydra.experimental.initialize() is no longer experimental. Use hydra.initialize()
  deprecation_warning(message=message)
/usr/local/lib/python3.8/dist-packages/hydra/experimental/initialize.py:45: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  self.delegate = real_initialize(
/usr/local/lib/python3.8/dist-packages/hydra/experimental/compose.py:25: UserWarning: hydra.experimental.compose() is no longer experimental. Use hydra.compose()
  deprecation_warning(message=message)
/usr/local/lib/python3.8/dist-packages/hydra/core/default_element.py:124: UserWarning: In 'config': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
sys:1: UserWarning: 
'config' is validated against ConfigStore schema with the same name.
This behavior is deprecated in Hydra 1.1 and will be removed in Hydra 1.2.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/automatic_schema_matching for migration instructions.
/usr/local/lib/python3.8/dist-packages/hydra/compose.py:52: UserWarning: 
The strict flag in the compose API is deprecated.
See https://hydra.cc/docs/upgrades/0.11_to_1.0/strict_mode_flag_deprecated for more info.

  deprecation_warning(
/usr/local/lib/python3.8/dist-packages/hydra/experimental/initialize.py:43: UserWarning: hydra.experimental.initialize() is no longer experimental. Use hydra.initialize()
  deprecation_warning(message=message)
/usr/local/lib/python3.8/dist-packages/hydra/experimental/initialize.py:45: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  self.delegate = real_initialize(
/usr/local/lib/python3.8/dist-packages/hydra/experimental/compose.py:25: UserWarning: hydra.experimental.compose() is no longer experimental. Use hydra.compose()
  deprecation_warning(message=message)
/usr/local/lib/python3.8/dist-packages/hydra/core/default_element.py:124: UserWarning: In 'config': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
sys:1: UserWarning: 
'config' is validated against ConfigStore schema with the same name.
This behavior is deprecated in Hydra 1.1 and will be removed in Hydra 1.2.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/automatic_schema_matching for migration instructions.
/usr/local/lib/python3.8/dist-packages/hydra/compose.py:52: UserWarning: 
The strict flag in the compose API is deprecated.
See https://hydra.cc/docs/upgrades/0.11_to_1.0/strict_mode_flag_deprecated for more info.

  deprecation_warning(
/usr/local/lib/python3.8/dist-packages/hydra/experimental/initialize.py:43: UserWarning: hydra.experimental.initialize() is no longer experimental. Use hydra.initialize()
  deprecation_warning(message=message)
/usr/local/lib/python3.8/dist-packages/hydra/experimental/initialize.py:45: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  self.delegate = real_initialize(
/usr/local/lib/python3.8/dist-packages/hydra/experimental/compose.py:25: UserWarning: hydra.experimental.compose() is no longer experimental. Use hydra.compose()
  deprecation_warning(message=message)
/usr/local/lib/python3.8/dist-packages/hydra/core/default_element.py:124: UserWarning: In 'config': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
sys:1: UserWarning: 
'config' is validated against ConfigStore schema with the same name.
This behavior is deprecated in Hydra 1.1 and will be removed in Hydra 1.2.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/automatic_schema_matching for migration instructions.
/usr/local/lib/python3.8/dist-packages/hydra/compose.py:52: UserWarning: 
The strict flag in the compose API is deprecated.
See https://hydra.cc/docs/upgrades/0.11_to_1.0/strict_mode_flag_deprecated for more info.

  deprecation_warning(
Traceback (most recent call last):
  File "./slurm_snapshot_code/2023-02-08T14_51_26.242208/train.py", line 14, in <module>
    cli_main()
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq_cli/train.py", line 636, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/distributed/utils.py", line 371, in call_main
    distributed_main(cfg.distributed_training.device_id, main, cfg, kwargs)
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/distributed/utils.py", line 345, in distributed_main
    main(cfg, **kwargs)
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq_cli/train.py", line 95, in main
    task = tasks.setup_task(cfg.task)
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/tasks/__init__.py", line 46, in setup_task
    return task.setup_task(cfg, **kwargs)
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/tasks/translation_multi_simple_epoch.py", line 151, in setup_task
    langs, dicts, training = MultilingualDatasetManager.prepare(
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/data/multilingual/multilingual_data_manager.py", line 619, in prepare
    dicts = cls.load_all_dictionaries(
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/data/multilingual/multilingual_data_manager.py", line 674, in load_all_dictionaries
    load_dicts(src_langs_to_load_dicts)
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/data/multilingual/multilingual_data_manager.py", line 656, in load_dicts
    dicts[lang] = load_dictionary(
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/data/multilingual/multilingual_data_manager.py", line 606, in load_dictionary_and_postproc
    d = load_dictionary(path)
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/tasks/fairseq_task.py", line 95, in load_dictionary
    return Dictionary.load(filename)
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/data/dictionary.py", line 228, in load
    d.add_from_file(f)
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/data/dictionary.py", line 241, in add_from_file
    raise fnfe
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/data/dictionary.py", line 238, in add_from_file
    with open(PathManager.get_local_path(f), "r", encoding="utf-8") as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/home/admin/khadija/prepare_data_output/data_bin/shard000/dict.ary_Arab.txt'
Traceback (most recent call last):
  File "./slurm_snapshot_code/2023-02-08T14_51_26.242208/train.py", line 14, in <module>
    cli_main()
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq_cli/train.py", line 636, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/distributed/utils.py", line 371, in call_main
    distributed_main(cfg.distributed_training.device_id, main, cfg, kwargs)
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/distributed/utils.py", line 345, in distributed_main
    main(cfg, **kwargs)
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq_cli/train.py", line 95, in main
    task = tasks.setup_task(cfg.task)
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/tasks/__init__.py", line 46, in setup_task
    return task.setup_task(cfg, **kwargs)
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/tasks/translation_multi_simple_epoch.py", line 151, in setup_task
    langs, dicts, training = MultilingualDatasetManager.prepare(
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/data/multilingual/multilingual_data_manager.py", line 619, in prepare
    dicts = cls.load_all_dictionaries(
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/data/multilingual/multilingual_data_manager.py", line 674, in load_all_dictionaries
    load_dicts(src_langs_to_load_dicts)
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/data/multilingual/multilingual_data_manager.py", line 656, in load_dicts
    dicts[lang] = load_dictionary(
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/data/multilingual/multilingual_data_manager.py", line 606, in load_dictionary_and_postproc
    d = load_dictionary(path)
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/tasks/fairseq_task.py", line 95, in load_dictionary
    return Dictionary.load(filename)
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/data/dictionary.py", line 228, in load
    d.add_from_file(f)
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/data/dictionary.py", line 241, in add_from_file
    raise fnfe
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/data/dictionary.py", line 238, in add_from_file
    with open(PathManager.get_local_path(f), "r", encoding="utf-8") as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/home/admin/khadija/prepare_data_output/data_bin/shard000/dict.ary_Arab.txt'
Traceback (most recent call last):
  File "./slurm_snapshot_code/2023-02-08T14_51_26.242208/train.py", line 14, in <module>
    cli_main()
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq_cli/train.py", line 636, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/distributed/utils.py", line 371, in call_main
    distributed_main(cfg.distributed_training.device_id, main, cfg, kwargs)
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/distributed/utils.py", line 345, in distributed_main
    main(cfg, **kwargs)
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq_cli/train.py", line 95, in main
    task = tasks.setup_task(cfg.task)
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/tasks/__init__.py", line 46, in setup_task
    return task.setup_task(cfg, **kwargs)
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/tasks/translation_multi_simple_epoch.py", line 151, in setup_task
    langs, dicts, training = MultilingualDatasetManager.prepare(
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/data/multilingual/multilingual_data_manager.py", line 619, in prepare
    dicts = cls.load_all_dictionaries(
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/data/multilingual/multilingual_data_manager.py", line 674, in load_all_dictionaries
    load_dicts(src_langs_to_load_dicts)
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/data/multilingual/multilingual_data_manager.py", line 656, in load_dicts
    dicts[lang] = load_dictionary(
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/data/multilingual/multilingual_data_manager.py", line 606, in load_dictionary_and_postproc
    d = load_dictionary(path)
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/tasks/fairseq_task.py", line 95, in load_dictionary
    return Dictionary.load(filename)
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/data/dictionary.py", line 228, in load
    d.add_from_file(f)
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/data/dictionary.py", line 241, in add_from_file
    raise fnfe
  File "/home/admin/khadija/fairseq/slurm_snapshot_code/2023-02-08T14_51_26.242208/fairseq/data/dictionary.py", line 238, in add_from_file
    with open(PathManager.get_local_path(f), "r", encoding="utf-8") as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/home/admin/khadija/prepare_data_output/data_bin/shard000/dict.ary_Arab.txt'
srun: error: slurmnode1: tasks 0-2: Exited with exit code 1
slurmstepd-slurmnode1: error: *** JOB 315 ON slurmnode1 CANCELLED AT 2023-02-08T14:54:23 **

Is Fairseq compatible with the new version of Stopes? 
@Mortimerp9 @kauterry @gwenzek Can you help me please?

**Comment by robotsp** [comment]
@ibtiRaj have you solve your problem?

**Comment by ibtiRaj** [comment]
@robotsp No, I didn't, I'm sorry.

**Comment by robotsp** [comment]
No worries. BTW, may I ask the model file and vocab file in your configs, are they the same as the original ones from NLLB?

**Comment by robotsp** [comment]
> @robotsp No, I didn't, I'm sorry.

No worries. BTW, may I ask the model file and vocab file in your configs, are they the same as the original ones from NLLB? @ibtiRaj

**Comment by ibtiRaj** [comment]
@robotsp  Yes, you are right, the vocabulary size is 255997 but when I run the fine tuning, I get a vocabulary size mismatch error :

![image](https://user-images.githubusercontent.com/50990415/220300276-62857b5f-da53-43ff-9729-fc1d1bc18fa9.png)

That's why I thought of adding 200 tokens to the original vocabulary.

**Comment by kauterry** [comment]
Hi @ibtiRaj! The `stopes/pipelines/prepare_data` pipeline has been completely refactored. Could you pull the latest version of the code and change your config format to be compatible with the new code? Here is the README explaining how to write a prepare_data config: https://github.com/facebookresearch/stopes/tree/main/stopes/pipelines/prepare_data

Once you re-prepare your data with the latest code and the changed config, let me know if you still face any issues.

**Comment by robotsp** [comment]
@kauterry Would you please have a look at https://github.com/facebookresearch/fairseq/issues/4989
I prepare my data with the latest code of stopes and the changed config, but came across the new issue of "Can't instantiate abstract class TrainModule with abstract methods requirements".

**Comment by ibtiRaj** [comment]
Hi @kauterry , thank you for your answer. 

When I prepare my data with the new version of stopes, I always get two errors:

- The first one is the same as in this issue https://github.com/facebookresearch/fairseq/issues/4989. I solved this error by using the old version of stopes.
- The second is the following :

![image](https://user-images.githubusercontent.com/50990415/220566870-a7737279-95a4-491b-91d1-01a053f4bd48.png)

 what do you think?

And what about the mismatch error, is it true that 200 new words can be added to the original vocabulary?

**Comment by robotsp** [comment]
I don't found nllb module in fairseq of the version ==0.12.1 that recommended by Stopes (https://github.com/facebookresearch/stopes/tree/main).  But when I reinstalled the nllb version of fairseq. Some conflicts of between hydra-core and fairseq occur. Do you know why? @kauterry

**Comment by robotsp** [comment]
I don't found nllb module in fairseq/examples of the version ==0.12.1 that recommended by the new version of Stopes (https://github.com/facebookresearch/stopes/tree/main). But when I reinstalled the nllb version of fairseq. Some conflicts of between hydra-core and fairseq occur. Do you know why? @kauterry @ibtiRaj

**Comment by ibtiRaj** [comment]
hi @robotsp, I solved the problem by following the NLLB installation guide here: https://github.com/facebookresearch/fairseq/blob/nllb/INSTALL.md.

**Comment by abumafrim** [comment]
Hi,

I used the configuration above to prepare my dataset for fine-tuning NLLB, but I kept getting "Empty Training Data" error. My source and target sentences are in separate text files. I tried compressing to .gz, but it kept giving me the same error.

Can you help me get this right? Thank you all.
