### ISSUE TITLE
Unable to run Demo present in demo folder.

### ISSUE THREAD

**Issue by oneraghavan** [facebookresearch/stopes#3]
I am trying to run the demo bitext mining given in demo folder . 

It is failing with following error :

2022-07-13 14:14 ERROR 1323129:submitit - Submitted job triggered an exception
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/nlsasfs/home/trial_home/trial_user/.local/lib/python3.8/site-packages/submitit/core/_submit.py", line 11, in <module>
    submitit_main()
  File "/nlsasfs/home/trial_home/trial_user/.local/lib/python3.8/site-packages/submitit/core/submission.py", line 72, in submitit_main
    process_job(args.folder)
  File "/nlsasfs/home/trial_home/trial_user/.local/lib/python3.8/site-packages/submitit/core/submission.py", line 65, in process_job
    raise error
  File "/nlsasfs/home/trial_home/trial_user/.local/lib/python3.8/site-packages/submitit/core/submission.py", line 54, in process_job
    result = delayed.result()
  File "/nlsasfs/home/trial_home/trial_user/.local/lib/python3.8/site-packages/submitit/core/utils.py", line 133, in result
    self._result = self.function(*self.args, **self.kwargs)
  File "/nlsasfs/home/trial_home/trial_user/indicmining/repos/stopes/stopes/core/stopes_module.py", line 94, in __call__
    res = self.run(iteration_value=iteration_value, iteration_index=iteration_index)
  File "/nlsasfs/home/trial_home/trial_user/indicmining/repos/stopes/stopes/modules/preprocess/line_processor.py", line 138, in run
    enc.process_lines(lines_with_numbers)
  File "/nlsasfs/home/trial_home/trial_user/indicmining/repos/stopes/stopes/modules/preprocess/encode_to_npy.py", line 58, in process_lines
    array = self.encode_to_np(lines_with_number)
  File "/nlsasfs/home/trial_home/trial_user/indicmining/repos/stopes/stopes/modules/preprocess/laser_sentence_encoder.py", line 397, in encode_to_np
    return self.encoder.encode_sentences(tokenized_sents)
  File "/nlsasfs/home/trial_home/trial_user/indicmining/repos/stopes/stopes/modules/preprocess/laser_sentence_encoder.py", line 156, in encode_sentences
    results.append(self._process_batch(batch))
  File "/nlsasfs/home/trial_home/trial_user/indicmining/repos/stopes/stopes/modules/preprocess/laser_sentence_encoder.py", line 95, in _process_batch
    sentemb = self.encoder(tokens, lengths)["sentemb"]
  File "/nlsasfs/home/trial_home/trial_user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nlsasfs/home/trial_home/trial_user/indicmining/repos/stopes/stopes/modules/preprocess/laser_sentence_encoder.py", line 200, in forward
    encoder_out = super().forward(src_tokens, src_lengths)
  File "/nlsasfs/home/trial_home/trial_user/.local/lib/python3.8/site-packages/fairseq/models/transformer/transformer_encoder.py", line 165, in forward
    return self.forward_scriptable(
  File "/nlsasfs/home/trial_home/trial_user/.local/lib/python3.8/site-packages/fairseq/models/transformer/transformer_encoder.py", line 294, in forward_scriptable
    lr = layer(x, encoder_padding_mask=encoder_padding_mask_out)
  File "/nlsasfs/home/trial_home/trial_user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nlsasfs/home/trial_home/trial_user/.local/lib/python3.8/site-packages/fairseq/modules/transformer_layer.py", line 319, in forward
    output = torch._transformer_encoder_layer_fwd(
RuntimeError: Mask shape should match input shape; transformer_mask is not supported in the fallback case.

**Comment by gwenzek** [comment]
Thanks for the report. Could you share the fairseq version you're using ? `pip show fairseq` and how you installed it ?

**Comment by oneraghavan** [comment]
Version: 0.12.2

**Comment by oneraghavan** [comment]
@gwenzek  Any further steps to fix this ?

**Comment by Mortimerp9** [comment]
@oneraghavan could you send the config that you used?

the run should have created a `outputs` folder and in there you will find (under the timestamp folder) a config dump folder with a bunch of yaml file. Would be good to have this + the cli you used.

**Comment by Mortimerp9** [comment]
@oneraghavan, I found an issue with the `demo.yaml` and `nl` file specs, I sent a fix for that, but if you got to the encoding step, then you must have fixed it on your side I guess.

I am running the encoders fine with fairseq==0.12.2 right now and that's working fine.

Can you maybe give us some details on your config/etc.

**Comment by Mortimerp9** [comment]
ok, bar that, I managed to get the same failure as you.

**Comment by Mortimerp9** [comment]
I'll update the readme to make sure that it's clear this should be the tag to use in fairseq repo.

**Comment by Mortimerp9** [comment]
fixed in 7e8518647e53c5a931c6e1229963e4e810b528cf
